# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: libGDX

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        
    - name: Make gradle executable
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Package JAR file
      run: ./gradlew dist

    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test
        build-root-directory: libGDX/

    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: desktop-1.0-jar
        path: /home/runner/work/PiazzaPanicAssessement2/PiazzaPanicAssessement2/libGDX/desktop/build/libs/desktop-1.0.jar
        
    - name: List files in directory
      run: |
        ls -R ${{ github.workspace }}
